#! /bin/bash
# add hybrid/integrated swapper
DEVICES="$(lspci | grep -i vga | grep -vi 'non-vga' | wc -l)"


# Workaround X11 Desktop detection issue
echo "$DESKTOP_SESSION" > /tmp/desktop-session
# Activate/Deactivate supergfxctl-gex in gnome sessions
if [ $? -eq 0 ]; then
	if cat /tmp/desktop-session | grep -E '(pika|vrr)' > /dev/null 2>&1
	then
		if [ $DEVICES -lt 1 ]
		then
			gnome-extensions enable supergfxctl-gex@asus-linux.org
			rm /tmp/desktop-session
		else
			gnome-extensions disable supergfxctl-gex@asus-linux.org
			rm /tmp/desktop-session
		fi
	 fi
fi
