opt/mutter-vrr/bin/gnome-extensions
opt/mutter-vrr/bin/gnome-shell
opt/mutter-vrr/bin/gnome-shell-extension-tool
opt/mutter-vrr/bin/gnome-shell-perf-tool
opt/mutter-vrr/lib/gnome-shell
opt/mutter-vrr/libexec
opt/mutter-vrr/share/applications/evolution-calendar.desktop
opt/mutter-vrr/share/applications/org.gnome.Shell*.desktop
opt/mutter-vrr/share/bash-completion/completions/gnome-extensions
opt/mutter-vrr/share/dbus-1/services
opt/mutter-vrr/share/man
opt/mutter-vrr/share/xdg-desktop-portal
debian/extras/gnome-shell-vrr usr/bin/
debian/extras/gnome-vrr.Shell.desktop usr/share/applications
