#!/bin/sh

set -e

# Enable systemd service

systemctl enable --now amdgpu-pro-lib.service || echo "amdgpu-pro-lib service could not be enabled"

# Add firmware

rm -r /usr/src/amdgpu-official || echo

ln -s  /usr/src/"$(ls /usr/src/ | grep amdgpu- | sort -nr | head -n1)" /usr/src/amdgpu-official

rm -r /usr/lib/firmware/amdgpu || echo

ln -s /usr/src/amdgpu-official/firmware/amdgpu /usr/lib/firmware/

update-initramfs -c -k all

#
