#! /bin/bash

# Undo the calamares sources modifactions

printf "## This file is deprecated in PikaOS.\n## See /etc/apt/sources.list.d/system.sources." | tee /etc/apt/sources.list > /dev/null

rm -rfv /etc/apt/sources.list.d/pika.list > /dev/null
